import { ChangeEvent, SetStateAction, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [inputText, setInputText] = useState('');
    const [inputVibe, setInputVibe] = useState('');
    const [formattedText, setFormattedText] = useState('');
    const [loading, setLoading] = useState(false);

    const updateInputText = (e: ChangeEvent<HTMLTextAreaElement>) => {
        if (e && e.target) {
            setInputText(e.target.value);
        }
    };

    const updateInputVibe = (e: ChangeEvent<HTMLInputElement>) => {
        if (e && e.target) {
            setInputVibe(e.target.value);
        }
    };

    const formatText = async () => {
        if (inputText && inputText.length < 3000 && inputVibe) {
            setLoading(true);

            let response = await fetch("/api/formatText", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                  },
                  body: JSON.stringify({
                    'vibe': inputVibe,
                    'context': inputText 
                  })
            });
            
            // success
            if(response.ok) {
                let data = await response.json();
                console.log(data);
                let result = data.choices[0];

                if(result && result.finish_reason === 'stop') {
                    setFormattedText(result.text);
                }
            }

            setLoading(false);
        } else {
            console.log('Input invalid');
        }
    };

    return (
        <>
            <Head>
                <title>Format Text</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.appContainer}>
                    <div>
                        <h5>Enter your text (2000 characters limit):</h5>
                        <textarea rows={10} cols={50} maxLength={2000} onChange={updateInputText}></textarea>
                        <input type='text' placeholder='Type vibe..' onChange={updateInputVibe} />
                        <button onClick={formatText}>Format</button>
                    </div>
                    <div className={styles.appResult}>
                        <h5>Result:</h5>
                        <textarea rows={10} cols={50} maxLength={3000} value={loading ? "Loading..." : formattedText.trim()} readOnly></textarea>
                    </div>
                </div>
            </main>
        </>
    )
}